#!/usr/bin/env python3
"""
Tests for Hermes Adapter.

Run with: python3 -m pytest services/home-miner-daemon/tests/test_hermes.py -v
"""

import json
import os
import sys
import tempfile
import pytest
from datetime import datetime, timezone, timedelta
from unittest.mock import patch, MagicMock

# Add service to path
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

# Set up test state directory
test_state_dir = tempfile.mkdtemp()
os.environ['ZEND_STATE_DIR'] = test_state_dir

import hermes
from hermes import (
    HermesConnection,
    HermesUnauthorizedError,
    HermesInvalidTokenError,
    HermesError,
    connect,
    pair_hermes,
    read_status,
    append_summary,
    get_filtered_events,
    HERMES_CAPABILITIES,
    HERMES_READABLE_EVENTS,
)
import spine
from spine import EventKind


class TestHermesConnect:
    """Tests for hermes.connect() function."""

    def test_hermes_connect_valid(self):
        """Connect with valid token succeeds."""
        # Create a valid token
        token = hermes.create_authority_token("hermes-001", ["observe", "summarize"], 24)
        
        connection = connect(token)
        
        assert connection.hermes_id == "hermes-001"
        assert connection.principal_id is not None  # Generated by store
        assert "observe" in connection.capabilities
        assert "summarize" in connection.capabilities
        assert connection.authority_scope == "observe+summarize"

    def test_hermes_connect_expired(self):
        """Connect with expired token fails."""
        import base64
        token_data = {
            "hermes_id": "hermes-001",
            "principal_id": "principal-001",
            "capabilities": ["observe"],
            "expires_at": (datetime.now(timezone.utc) - timedelta(hours=1)).isoformat()
        }
        token = base64.b64encode(json.dumps(token_data).encode()).decode()
        
        with pytest.raises(HermesInvalidTokenError) as exc_info:
            connect(token)
        
        assert "expired" in str(exc_info.value).lower()

    def test_hermes_connect_malformed_token(self):
        """Reject tokens that aren't valid Base64 JSON."""
        with pytest.raises(HermesInvalidTokenError):
            connect("not-valid-base64!!!")

    def test_hermes_connect_missing_fields(self):
        """Reject tokens missing required fields."""
        import base64
        # Missing capabilities
        token_data = {
            "hermes_id": "hermes-001",
            "principal_id": "principal-001",
            "expires_at": (datetime.now(timezone.utc) + timedelta(hours=24)).isoformat()
        }
        token = base64.b64encode(json.dumps(token_data).encode()).decode()
        
        with pytest.raises(HermesInvalidTokenError) as exc_info:
            connect(token)
        
        assert "capabilities" in str(exc_info.value)

    def test_hermes_invalid_capability(self):
        """Reject tokens with invalid Hermes capabilities."""
        import base64
        token_data = {
            "hermes_id": "hermes-001",
            "principal_id": "principal-001",
            "capabilities": ["observe", "control"],  # control not allowed for Hermes
            "expires_at": (datetime.now(timezone.utc) + timedelta(hours=24)).isoformat()
        }
        token = base64.b64encode(json.dumps(token_data).encode()).decode()
        
        with pytest.raises(HermesInvalidTokenError) as exc_info:
            connect(token)
        
        assert "control" in str(exc_info.value).lower()

    def test_hermes_read_status(self):
        """Observe capability allows status read (no exception)."""
        token = hermes.create_authority_token("hermes-002", ["observe"], 24)
        connection = connect(token)
        
        # Test that read_status can be called with observe capability
        # We can't test the actual return value without running daemon,
        # but we can verify it doesn't raise HermesUnauthorizedError
        try:
            # This will fail because daemon.miner isn't running, but it should
            # not raise HermesUnauthorizedError (which would mean capability check failed)
            status = read_status(connection)
        except HermesUnauthorizedError:
            pytest.fail("read_status raised HermesUnauthorizedError for observe-capable connection")
        except Exception:
            # Expected - daemon.miner isn't available in test
            pass  # This is expected in unit tests without daemon
        
        # Verify capability is present
        assert "observe" in connection.capabilities

    def test_hermes_no_observe_capability(self):
        """Read status fails without observe capability."""
        import base64
        token_data = {
            "hermes_id": "hermes-003",
            "principal_id": "principal-001",
            "capabilities": [],  # No observe
            "expires_at": (datetime.now(timezone.utc) + timedelta(hours=24)).isoformat()
        }
        token = base64.b64encode(json.dumps(token_data).encode()).decode()
        connection = connect(token)
        
        with pytest.raises(HermesUnauthorizedError) as exc_info:
            read_status(connection)
        
        assert "observe" in str(exc_info.value).lower()


class TestHermesSummary:
    """Tests for hermes.append_summary() function."""

    def test_hermes_append_summary(self):
        """Summarize capability appends to spine."""
        token = hermes.create_authority_token("hermes-010", ["summarize"], 24)
        connection = connect(token)
        
        result = append_summary(
            connection,
            "Miner running normally at 50kH/s",
            "observe"
        )
        
        assert result["appended"] is True
        assert "event_id" in result
        
        # Verify event in spine
        events = spine.get_events(kind=EventKind.HERMES_SUMMARY, limit=1)
        assert len(events) > 0
        assert events[0].payload["summary_text"] == "Miner running normally at 50kH/s"
        assert events[0].payload["hermes_id"] == "hermes-010"

    def test_hermes_no_summarize_capability(self):
        """Append summary fails without summarize capability."""
        import base64
        token_data = {
            "hermes_id": "hermes-011",
            "principal_id": "principal-001",
            "capabilities": ["observe"],  # No summarize
            "expires_at": (datetime.now(timezone.utc) + timedelta(hours=24)).isoformat()
        }
        token = base64.b64encode(json.dumps(token_data).encode()).decode()
        connection = connect(token)
        
        with pytest.raises(HermesUnauthorizedError) as exc_info:
            append_summary(connection, "Test summary", "observe")
        
        assert "summarize" in str(exc_info.value).lower()

    def test_hermes_empty_summary_rejected(self):
        """Empty summary text is rejected."""
        token = hermes.create_authority_token("hermes-012", ["summarize"], 24)
        connection = connect(token)
        
        with pytest.raises(HermesError) as exc_info:
            append_summary(connection, "", "observe")
        
        assert "empty" in str(exc_info.value).lower()


class TestHermesEventFilter:
    """Tests for hermes.get_filtered_events() function."""

    def test_hermes_event_filter(self):
        """user_message events are filtered out."""
        token = hermes.create_authority_token("hermes-020", ["observe"], 24)
        connection = connect(token)
        
        # Create some events including user_message
        principal_id = connection.principal_id
        spine.append_event(EventKind.HERMES_SUMMARY, principal_id, {"test": "hermes_summary"})
        spine.append_event(EventKind.MINER_ALERT, principal_id, {"test": "miner_alert"})
        spine.append_event(EventKind.USER_MESSAGE, principal_id, {"test": "user_message"})
        spine.append_event(EventKind.CONTROL_RECEIPT, principal_id, {"test": "control_receipt"})
        
        events = get_filtered_events(connection, limit=10)
        
        # Verify no user_message events
        event_kinds = [e["kind"] for e in events]
        assert "user_message" not in event_kinds
        assert "hermes_summary" in event_kinds
        assert "miner_alert" in event_kinds
        assert "control_receipt" in event_kinds

    def test_hermes_summary_appears_in_inbox(self):
        """Appended summary is visible via filtered events."""
        token = hermes.create_authority_token("hermes-021", ["observe", "summarize"], 24)
        connection = connect(token)
        
        # Append a summary
        result = append_summary(connection, "Miner health check passed", "observe")
        
        # Read filtered events
        events = get_filtered_events(connection, limit=100)  # Higher limit to find it
        
        # Find the summary we just appended by event_id
        summary_event = next((e for e in events if e["id"] == result["event_id"]), None)
        assert summary_event is not None
        assert summary_event["payload"]["summary_text"] == "Miner health check passed"


class TestHermesPairing:
    """Tests for hermes.pair_hermes() function."""

    def test_hermes_pair_creates_record(self):
        """Pairing creates a Hermes pairing record."""
        pairing = pair_hermes("hermes-pair-001", "test-hermes")
        
        assert pairing.hermes_id == "hermes-pair-001"
        assert pairing.device_name == "test-hermes"
        assert "observe" in pairing.capabilities
        assert "summarize" in pairing.capabilities
        assert pairing.token is not None

    def test_hermes_pair_idempotent(self):
        """Pairing is idempotent - same hermes_id returns existing."""
        pair_hermes("hermes-pair-002", "test-hermes-2")
        pairing2 = pair_hermes("hermes-pair-002", "test-hermes-2-different")
        
        # Should return same pairing, ignore new device_name
        assert pairing2.hermes_id == "hermes-pair-002"


class TestHermesCapabilities:
    """Tests for capability boundaries."""

    def test_hermes_capabilities_constant(self):
        """HERMES_CAPABILITIES contains expected values."""
        assert "observe" in HERMES_CAPABILITIES
        assert "summarize" in HERMES_CAPABILITIES
        assert "control" not in HERMES_CAPABILITIES

    def test_hermes_readable_events_constant(self):
        """HERMES_READABLE_EVENTS contains expected values."""
        event_values = [e.value for e in HERMES_READABLE_EVENTS]
        assert "hermes_summary" in event_values
        assert "miner_alert" in event_values
        assert "control_receipt" in event_values
        assert "user_message" not in event_values


class TestHermesControlBoundary:
    """Tests for control boundary enforcement."""

    def test_hermes_cannot_have_control_capability(self):
        """Tokens with control capability are rejected."""
        import base64
        token_data = {
            "hermes_id": "hermes-control-001",
            "principal_id": "principal-001",
            "capabilities": ["observe", "summarize", "control"],
            "expires_at": (datetime.now(timezone.utc) + timedelta(hours=24)).isoformat()
        }
        token = base64.b64encode(json.dumps(token_data).encode()).decode()
        
        with pytest.raises(HermesInvalidTokenError) as exc_info:
            connect(token)
        
        assert "control" in str(exc_info.value).lower()


if __name__ == '__main__':
    pytest.main([__file__, '-v'])
